service: develofolio-server

provider:
  name: aws
  runtime: nodejs14.x
  region: ap-northeast-2

plugins:
  - serverless-plugin-warmup

custom:
  warmup:
    main:
      enabled: true

package:
  individually: true
  exclude:
    - src/*.ts
    - node_modules/.bin/**

functions:
  main:
    handler: dist/serverless.handler
    events:
      - http:
          method: ANY
          path: /
      - http:
          method: ANY
          path: '{proxy+}'
    timeout: 60
    warmup: true
