service:
  name: develofolio-server

provider:
  name: aws
  runtime: nodejs14.x
  region: ap-northeast-2
  profile: chojonghoon
  vpc:
    securityGroupIds:
      - sg-0fc4c2d911354af10
    subnetIds:
      - subnet-08b3c8973d16d70e6
      - subnet-047203ac3a392eedf

package:
  individually: true
  exclude:
    - src/*.ts
    - node_modules/.bin/**

functions:
  main:
    handler: dist/serverless.handler
    events:
      - http:
          method: ANY
          path: /
      - http:
          method: ANY
          path: '{proxy+}'
    timeout: 60
