name: Deploy Client

on:
  push:
    branches: [main]
    paths:
      - 'packages/client/**'
      - '.github/workflows/deploy-client.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Check cached yarn.lock
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}-${{ hashFiles('packages/client/patches/**') }} }}

      - name: Install NPM dependencies
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn install
        working-directory: ./packages/client

      - name: Create env file
        run: |
          touch .env
          echo "NEXT_PUBLIC_CLIENT_HOST=https://develofolio.com" >> .env
          echo "NEXT_PUBLIC_SERVER_HOST=https://api.develofolio.com" >> .env
          echo "NEXT_PUBLIC_IMAGES_HOST=https://images.develofolio.com" >> .env
          echo "NEXT_PUBLIC_OG_IMAGE_HOST=https://og-image.develofolio.com" >> .env
          echo "NEXT_PUBLIC_GA_TRACKING_ID=G-C4H566WCEC" >> .env
        working-directory: ./packages/client

      - name: Build package
        run: |
          yarn codegen
          yarn build
        working-directory: ./packages/client

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Deploy Next.js app
        run: yarn deploy
        working-directory: ./packages/client
