name: Deploy image-resizer

on:
  push:
    branches: [release]
    paths:
      - 'packages/image-resizer/**'
      - '.github/workflows/deploy-image-resizer.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install NPM dependencies
        run: env npm_config_arch=x64 npm_config_platform=linux yarn install
        working-directory: ./packages/image-resizer

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Deploy ImageResizer
        run: yarn deploy
        working-directory: ./packages/image-resizer
